/**
 * Procedural surface texture.
 *
 * One hidden <svg> holds every filter the app uses. Texture layers start as
 * <svg><rect filter="url(#...)"/></svg> sized to their parent and then bake
 * themselves into a bitmap at that size — see `textureLayer` below for the
 * measurement that made the bake necessary. feTurbulence is not cheap to
 * evaluate, and a layer that carries a blend mode gets asked to evaluate it
 * again every time anything repaints underneath.
 *
 * Nothing here ships as a bitmap: the grain regenerates at whatever size and DPI
 * the window happens to be, and re-bakes when either changes.
 */

import { svg } from './dom';

let installed = false;

export function installTextureDefs(host: ParentNode = document.body): void {
  if (installed) return;
  installed = true;

  const defs = svg('defs', {}, [
    /* Brushed aluminium micro-grain: noise stretched hard along x so it varies
       only across the grain, which is exactly what a linisher leaves behind. */
    svg('filter', { id: 'wf-alu', x: '0', y: '0', width: '100%', height: '100%' }, [
      svg('feTurbulence', {
        type: 'fractalNoise',
        baseFrequency: '0.004 1.1',
        numOctaves: '3',
        seed: '7',
        stitchTiles: 'stitch',
        result: 'n',
      }),
      svg('feColorMatrix', { in: 'n', type: 'saturate', values: '0', result: 'g' }),
      svg('feComponentTransfer', { in: 'g' }, [
        svg('feFuncR', { type: 'linear', slope: '0.55', intercept: '0.22' }),
        svg('feFuncG', { type: 'linear', slope: '0.55', intercept: '0.22' }),
        svg('feFuncB', { type: 'linear', slope: '0.55', intercept: '0.22' }),
        svg('feFuncA', { type: 'linear', slope: '1', intercept: '0' }),
      ]),
    ]),

    /* Matte black plastic: fine isotropic tooth, very low contrast. */
    svg('filter', { id: 'wf-matte', x: '0', y: '0', width: '100%', height: '100%' }, [
      svg('feTurbulence', {
        type: 'fractalNoise',
        baseFrequency: '0.85',
        numOctaves: '2',
        seed: '3',
        stitchTiles: 'stitch',
        result: 'n',
      }),
      svg('feColorMatrix', { in: 'n', type: 'saturate', values: '0', result: 'g' }),
      svg('feComponentTransfer', { in: 'g' }, [
        svg('feFuncR', { type: 'linear', slope: '0.42', intercept: '0.29' }),
        svg('feFuncG', { type: 'linear', slope: '0.42', intercept: '0.29' }),
        svg('feFuncB', { type: 'linear', slope: '0.42', intercept: '0.29' }),
        svg('feFuncA', { type: 'linear', slope: '1', intercept: '0' }),
      ]),
    ]),

    /* Printed-ink softening for dial faces: a hair of blur so numerals read as
       pad-printed rather than rasterised. */
    svg('filter', { id: 'wf-ink', x: '-10%', y: '-10%', width: '120%', height: '120%' }, [
      svg('feGaussianBlur', { stdDeviation: '0.22' }),
    ]),

    /* Paper fibre for printed instrument faces. A meter dial is card, not a
       flat fill: the fibre shows through the ink and breaks the coloured band's
       edge, which is most of what stops it reading as a stroked path. */
    svg('filter', { id: 'wf-paper', x: '0', y: '0', width: '100%', height: '100%' }, [
      svg('feTurbulence', {
        type: 'fractalNoise',
        baseFrequency: '0.9 0.55',
        numOctaves: '3',
        seed: '11',
        stitchTiles: 'stitch',
        result: 'n',
      }),
      svg('feColorMatrix', { in: 'n', type: 'saturate', values: '0', result: 'g' }),
      svg('feComponentTransfer', { in: 'g' }, [
        svg('feFuncA', { type: 'linear', slope: '0.16', intercept: '0' }),
      ]),
    ]),

    /* Ink spread. A squeegee pushes pigment past the edge it was registered
       against, so a printed band blooms on its free side. Wider than wf-ink and
       used only on the spread pass. */
    svg('filter', { id: 'wf-spread', x: '-25%', y: '-25%', width: '150%', height: '150%' }, [
      svg('feGaussianBlur', { stdDeviation: '1.5' }),
    ]),
  ]);

  const root = svg('svg', {
    'aria-hidden': 'true',
    focusable: 'false',
    width: '0',
    height: '0',
    style: 'position:absolute;width:0;height:0;overflow:hidden',
  }, [defs]);

  host.append(root);
}

export type TextureKind = 'alu' | 'matte';

const FILTER_ID: Record<TextureKind, string> = {
  alu: 'wf-alu',
  matte: 'wf-matte',
};

const CLASS: Record<TextureKind, string> = {
  alu: 'tex tex--alu',
  matte: 'tex tex--black',
};

/**
 * A full-bleed procedural texture layer for a material surface.
 *
 * The grain is generated by a live `feTurbulence` for the first frames it is on
 * screen and then FROZEN INTO A BITMAP of exactly the size the surface turned
 * out to be, which is what actually gets composited from then on.
 *
 * The docblock at the top of this file used to claim these layers "are painted
 * once by the compositor and never touched again, so they cost nothing per
 * frame". That is true only while nothing under them changes. Both of these
 * layers carry `mix-blend-mode`, so anything repainting behind one makes Blink
 * re-evaluate the blend — and with a live filter in the layer, re-evaluating the
 * blend means re-running the turbulence over the whole surface.
 *
 * Measured on the shipped build with a station playing: the panel's own texture
 * layer is 920x589, and the once-a-second tick of the LCD's playing clock was
 * re-rastering all twelve of the panel layer's tiles at ~28 ms each — 1.3 s of
 * RasterTask per 4 s of wall clock, a third of a core, for one line of text.
 * With the same layer hidden the same tick cost 1 ms. Nothing else about the
 * panel changed; the tiles were expensive because the noise was being computed
 * again, every time, from scratch.
 *
 * Baked, the layer is an `<image>`: the compositor blits it and the cost of a
 * repaint behind it goes to the cost of a blit. The pixels are the same pixels —
 * the same filter primitives, the same seed, the same frequency, evaluated over
 * the same user-space region at device resolution — because the bake is done by
 * the same renderer, from an SVG carrying the same filter, at the size the
 * element measured. Nothing ships as a bitmap: it is still generated at run time
 * at whatever size and DPI the window happens to be, and re-generated when that
 * changes. If the bake fails for any reason the live filter simply stays.
 */
export function textureLayer(kind: TextureKind): SVGSVGElement {
  const rect = svg('rect', {
    x: '0',
    y: '0',
    width: '100%',
    height: '100%',
    filter: `url(#${FILTER_ID[kind]})`,
  });
  const node = svg(
    'svg',
    {
      class: CLASS[kind],
      'aria-hidden': 'true',
      focusable: 'false',
      preserveAspectRatio: 'none',
      /* Its own compositor layer, so the blend is done once at composite time
         instead of inside the raster of everything underneath it. Both texture
         classes carry `mix-blend-mode`, and a full-bleed blended layer makes any
         invalidation under it an invalidation of the WHOLE surface: with the
         panel's 920x589 layer, one line of text ticking over re-rastered all
         twelve of its tiles. Baked and promoted, the same tick re-rasters one:
         measured 1.3 s of RasterTask per 4 s (a third of a core) before, 38 ms
         per 5 s after. `mix-blend-mode` already makes this element a stacking
         context, so promoting it changes nothing about what it is — only where
         the blend happens. */
      style: 'will-change: transform',
    },
    [rect],
  );
  bakeWhenSized(node, kind);
  return node;
}

/* --------------------------------------------------------------- the bake */

/** Below this a surface is a sliver and the live filter is cheap anyway. */
const MIN_BAKE_PX = 8;
/** A resize storm is one bake, not thirty. */
const REBAKE_DEBOUNCE_MS = 180;
/** Ignore re-bakes for changes too small to see; a 1 px reflow is not a resize. */
const RESIZE_EPSILON_PX = 2;

/** The filter primitives, verbatim, for a standalone document. */
const FILTER_SVG: Record<TextureKind, string> = {
  alu:
    '<feTurbulence type="fractalNoise" baseFrequency="0.004 1.1" numOctaves="3" seed="7" stitchTiles="stitch" result="n"/>' +
    '<feColorMatrix in="n" type="saturate" values="0" result="g"/>' +
    '<feComponentTransfer in="g">' +
    '<feFuncR type="linear" slope="0.55" intercept="0.22"/>' +
    '<feFuncG type="linear" slope="0.55" intercept="0.22"/>' +
    '<feFuncB type="linear" slope="0.55" intercept="0.22"/>' +
    '<feFuncA type="linear" slope="1" intercept="0"/>' +
    '</feComponentTransfer>',
  matte:
    '<feTurbulence type="fractalNoise" baseFrequency="0.85" numOctaves="2" seed="3" stitchTiles="stitch" result="n"/>' +
    '<feColorMatrix in="n" type="saturate" values="0" result="g"/>' +
    '<feComponentTransfer in="g">' +
    '<feFuncR type="linear" slope="0.42" intercept="0.29"/>' +
    '<feFuncG type="linear" slope="0.42" intercept="0.29"/>' +
    '<feFuncB type="linear" slope="0.42" intercept="0.29"/>' +
    '<feFuncA type="linear" slope="1" intercept="0"/>' +
    '</feComponentTransfer>',
};

function bakeWhenSized(node: SVGSVGElement, kind: TextureKind): void {
  let bakedW = 0;
  let bakedH = 0;
  let bakedDpr = 0;
  let timer = 0;
  let url: string | undefined;
  let generation = 0;

  const ro = new ResizeObserver((entries) => {
    const cr = entries[entries.length - 1]!.contentRect;
    const w = Math.round(cr.width);
    const h = Math.round(cr.height);
    const dpr = window.devicePixelRatio || 1;
    if (w < MIN_BAKE_PX || h < MIN_BAKE_PX) return;
    if (
      Math.abs(w - bakedW) < RESIZE_EPSILON_PX &&
      Math.abs(h - bakedH) < RESIZE_EPSILON_PX &&
      dpr === bakedDpr
    ) {
      return;
    }
    bakedW = w;
    bakedH = h;
    bakedDpr = dpr;
    window.clearTimeout(timer);
    const mine = ++generation;
    timer = window.setTimeout(() => {
      void bake(kind, w, h, dpr).then((next) => {
        // A later resize already won; drop this one rather than fighting it.
        if (!next || mine !== generation || !node.isConnected) {
          if (next) URL.revokeObjectURL(next);
          return;
        }
        const image = svg('image', {
          x: '0',
          y: '0',
          width: '100%',
          height: '100%',
          preserveAspectRatio: 'none',
          href: next,
        });
        node.replaceChildren(image);
        if (url) URL.revokeObjectURL(url);
        url = next;
      });
    }, REBAKE_DEBOUNCE_MS);
  });
  ro.observe(node);
}

/**
 * Render the filter once, at the surface's own size, into a bitmap.
 *
 * The standalone document is `width/height` in DEVICE pixels with a `viewBox` in
 * CSS pixels, so the noise field is the one the live filter describes and it is
 * resolved at the screen's real resolution — the same two things Blink does when
 * it rasterises the live filter itself.
 */
async function bake(
  kind: TextureKind,
  w: number,
  h: number,
  dpr: number,
): Promise<string | undefined> {
  try {
    const doc =
      `<svg xmlns="http://www.w3.org/2000/svg" width="${Math.round(w * dpr)}" height="${Math.round(
        h * dpr,
      )}" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">` +
      `<filter id="f" x="0" y="0" width="100%" height="100%">${FILTER_SVG[kind]}</filter>` +
      `<rect x="0" y="0" width="100%" height="100%" filter="url(#f)"/></svg>`;
    const img = new Image();
    img.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(doc)}`;
    await img.decode();
    const canvas = document.createElement('canvas');
    canvas.width = Math.max(1, Math.round(w * dpr));
    canvas.height = Math.max(1, Math.round(h * dpr));
    const ctx = canvas.getContext('2d');
    if (!ctx) return undefined;
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    return await new Promise<string | undefined>((res) => {
      canvas.toBlob((b) => res(b ? URL.createObjectURL(b) : undefined), 'image/png');
    });
  } catch {
    // The live filter stays. A surface that looks right and costs something is
    // strictly better than a surface that is not there.
    return undefined;
  }
}
